### ISSUE TITLE
Estandarizar los parámetros de los selectores

### ISSUE THREAD

**Issue by SJMC29** [Carlosmtp/DomuzSGI#78]
- [x] Crear nueva tabla para la Periodicidad de nuestros indicadores.

- [x] Crear las funciones necesarias en la API.

- [x] Añadir parámetro al componente en el frontend.

**Comment by Carlosmtp** [comment]
@Git-Fanfo 

1. Se creó una nueva tabla en la base de datos llamada "periodicities" cuyos campos son id y name.
2. Se eliminó el campo "periodicity" de la tabla "process_indicators", y se reemplazó con el campo "periodicityId" que se relaciona con el id de la tabla "periodicities".
3. Se creó una función en la api para obtener la lista de periodicidades: "/get/periodicities/"
4. **URGENTE** modificar los selectores de periodicidades y el envío de datos para crear o modificar indicadores del frontend teniendo los en cuenta los cambios anteriormente mencionados.

**Comment by Carlosmtp** [comment]
@Git-Fanfo 
¿Se deberían hacer los mismos cambios para la tabla de indicadores de objetivos?
Si es así, por favor crear el issue y asignármelo.
:smile:

**Comment by Greater-Gold** [comment]
Sip, se debería entonces linkear periodicity tambien con los estratégicos
